kind: pipeline
name: default


workspace:
  path: /drone/src
  
steps:
- name: create-test
  image: blazerunner/blazemeter
  environment:   
    apikey: 38e53fd821771b102b5bfddc
    apisecret: c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50
    testname: Drone_Demo_5
    projectid: 961236
    createtest: true
    inputstartfile: BlazeDemo.yaml
    Uploadfilechk: true

