kind: pipeline
name: default


workspace:
  path: /drone/src

steps:
- name: create-test
  pull: always
  image: dnyaneshwarnagre/blazemeter:1.4.2
  environment:   
    apikey: 38e53fd821771b102b5bfddc
    apisecret: c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50
    testid: 10127108 
    modeldata: '{"email": "\"test123@test.com\"", "password": "\"123456\""}'
#     modeldata: '{"url": "\"https://blazedemo.com/\""}'
#     testname: Drone_Demo_4
#     projectid: 961236
#     createtest: false
#     inputstartfile: BlazeDemo.yaml
#     uploadfilechk: true
# F 10129962
# P 10127108
