kind: pipeline
name: default


workspace:
  path: /drone/src

steps:
- name: create-test
  image: dnyaneshwarnagre/blazemeter:testing
  environment:   
    apikey: 38e53fd821771b102b5bfddc
    apisecret: c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50
    testid: 10124705 #9998412 #9997714
    modeldata: '{"email": "\"test@mailinator.com\"", "password": "\"123456123\""}'
#     testname: Drone_Demo_4
#     projectid: 961236
#     createtest: false
#     inputstartfile: BlazeDemo.yaml
#     uploadfilechk: true


