kind: pipeline
name: default


workspace:
  path: /drone/src

steps:
- name: run-existing
  pull: always
  #image: dnyaneshwarnagre/blazemeter:1.4.5
  image: blazerunner/blazemeter:1.2
  #image: dnyaneshwarnagre/blazemeter:1.4.7
  environment:   
    apikey: 38e53fd821771b102b5bfddc
    apisecret: c9fb4b4be583657d952d3d25103b28590811e7b0f43bf8d7d9107b6345ae752f15a21d50
    #testid: 9535237 #10481630 #9535257 #9535204  #9535237 #9535204    # F 10129962 P 10132052
    showtaillog: false
    #modeldata: '{"email": "\"test@mail.com\"", "password": "\"123456\""}'
    #modeldata: '{"url": "\"https://blazedemo.com/\""}'
    
##### Update yml file
    uploadfilechk: true
    inputallfiles: dependencies #BlazeDemo.yaml
    env_variable: '{"username":"\"dn654\"","password":"\"abczyt\""}'
    
##### Create new test 
    createtest: true
    testname: "drone-test1"
    projectid: 961236
    inputstartfile: BlazeDemo.yaml
    #inputstartfile: /drone/src/dependencies/SampleAPIStrong.yaml
    
##### Download artifact set to false
    continuepipeline: false
    
##### Jmeter Properties
    jmeterproperties: "test=dronetest1"

##### Testing step for artifacts download
- name: display dirs
  image: alpine
  commands:
    - ls
    - pwd
    - ls ./tmp/artifacts
